### ISSUE TITLE
Should there be a noarch build ？

### ISSUE THREAD

**Issue by ivaquero** [conda-forge/sktime-feedstock#27]
Hi, dear maintainers, since the c dependencies have been replaced by numba, is it possible to add a noarch build, so that M1 Mac can use this package natively?

**Comment by lmmentel** [comment]
Thanks for your suggestion. The latest release is free of C and therefore you should be able to install on any platform (that python supports) with pip. We should be able to do that with conda but we might have to investigate how it affects the "all-extras" recipe since some of the deps are platform specific.

**Comment by ivaquero** [comment]
Thank you for the quick reply. Yes, I agree, since the “all-extras” recipe includes several packages that does not support arm64 for now (e.g., `prophet`), it might take some time to wait for all the packages getting ready.

Again, many thanks for the latest build.
